### ISSUE TITLE
Requests: Remove Airplane Icon When Ethernet Is Active, Offer Possibility To Hide Airplane Icon/Mode

### ISSUE THREAD

**Issue by jacob-emery** [Ordissimo/Big-Sur-StatusArea#44]
Would it be possible to hide the airplane icon from the network indicator when an Ethernet connection is active (with WiFi and Bluetooth disabled)? In this case an airplane icon is added alongside the Ethernet icon, and it feels a bit weird. Would it be possible to also remove "Airplane Mode On" from the Network indicator?

Actually, I would completely remove the text "Airplane Mode On" from the Network indicator at all times, even when there is no active Ethernet connection.
In the case of no WiFi, no Ethernet and no Bluetooth the Airplane Icon should still be displayed, but the text should be removed if you expand the indicator.

You could offer an option in the settings (for instance "Disable Airplane Mode") if you don't want this to be the default.

**Comment by Ordissimo** [comment]
hi @jacob-emery,
Can you tell me the version of the extension you use?

**Comment by jacob-emery** [comment]
It is version 23. The current one from https://extensions.gnome.org/.

I took a screenshot with wifi and bluetooth both disabled.
![Screenshot from 2021-06-17 22-20-45](https://user-images.githubusercontent.com/35579970/122467743-2dd99400-cfbb-11eb-9da2-73326da55db9.png)

**Comment by Ordissimo** [comment]
I need to know what version of gnome-shell you are running.
gnome-shell 3.38 uses Gtk 3
gnome-shell 40.x uses Gtk 4
Your distribution, etc...
I need to know your context to be able to reproduce and correct!
Thanks
Thierry

**Comment by jacob-emery** [comment]
Actually, I don't even consider this to be an issue anymore. It felt weird at first to see two icons inside the network indicator, but I already got used to it. Seeing the airplane also tells me that the WiFi is disabled (i.e. that I am using only an Ethernet cable).

However, I think it would be much clearer for the average person if:

- the airplane mode is not shown at all (only in the system settings... if one opens them)
- bluetooth icon needs to be disabled when bluetooth is disabled (point made already in the other request)
- wifi is not shown if it is disabled (instead is shown airplane mode if there is no active ethernet connection either, else the ethernet icon is shown)
- if ethernet and wifi are enabled at the same time, you see them both on the top bar (now one can only see ethernet) (like what happens already when one turns on the VPN)

This way I will not need to look at the airplane icon and say "mmmh... does that mean that bluetooth and wifi are disabled?" — instead it will be completely clear. Especially for people that don't understand IT very well (I am planning to install this extension on my family members' PCs).

**Comment by jacob-emery** [comment]
I use Fedora 33 with the latest GNOME 3.38.x packages.

**Comment by jacob-emery** [comment]
Since I am in the middle of my exams session, for three more weeks I will not be able to test on Fedora 34 (Gnome 40.x). But I'll do it as soon as I can :)

**Comment by jacob-emery** [comment]
Thank you for considering my proposal!
However, if some object pieces are hard coded also in this case and they would make he extension impossible to maintain... then never mind.
Thank you for offering us this great extension.

**Comment by Ordissimo** [comment]
I have reproduced, thank you, I will try to correct!

**Comment by Ordissimo** [comment]
Hi @jacob-emery,
It is corrected, you must wait for the publication by gnome-extensions of the new extensions, I let you close the issue, if it is corrected!

**Comment by Ordissimo** [comment]
The publication was faster than expected :grin:

**Comment by jacob-emery** [comment]
Unfortunately I can still see the airplane icon
![Screenshot from 2021-06-18 11-10-40](https://user-images.githubusercontent.com/35579970/122537473-e0ded780-d025-11eb-9280-a5079ac9d67a.png)

**Comment by jacob-emery** [comment]
I had a very quick look at the code and it appears to me that this._network._primaryIndicator.visible only considers the wifi interface. I could be wrong though.

I propose to leave this issue open for another 3 weeks and then, once I am finished with my exams, I'd love to help you debug and adjust the code for a better user experience.

**Comment by Ordissimo** [comment]
Ok for me and good luck with your examuns!

**Comment by Ordissimo** [comment]
No feedback

**Comment by jacob-emery** [comment]
Sorry, I forgot to give feedback. I tried to fix it, but without success. I should have closed the issue a long time ago...
